"""
E2E placeholder for the Chrome extension detection flow.

Requires a real Chrome instance + Playwright. Skipped unless `--run-e2e` is
passed. The actual test loads the unpacked extension at `extension/dist/`,
opens a fixture HTML page containing watermarked text (generated by the
Python encoder), and asserts the popup reports the correct issuer.
"""

import pytest


@pytest.mark.skip(reason="E2E requires Chrome+Playwright; run via `make test-e2e`")
def test_extension_badge_appears():
    pass
