"""Shared pytest fixtures for the Vellum test suite.

Forces fixture demo mode + simulated chain + disabled Auth0 for every test,
and provides an httpx AsyncClient bound to a freshly-built FastAPI app whose
lifespan handler runs (so app.state.services and friends exist).
"""

from __future__ import annotations

import hashlib
from typing import Any

import pytest
import pytest_asyncio
from asgi_lifespan import LifespanManager
from httpx import ASGITransport, AsyncClient


# ---------------------------------------------------------------------------
# Settings / env management
# ---------------------------------------------------------------------------


@pytest.fixture
def settings_env(tmp_path, monkeypatch):
    """Force demo+simulated env vars and a per-test SQLite database file."""
    db_path = tmp_path / "test.db"

    monkeypatch.setenv("DEMO_MODE", "fixture")
    monkeypatch.setenv("AUTH0_DOMAIN", "")
    monkeypatch.setenv("CHAIN_BACKEND", "simulated")
    monkeypatch.setenv("DB_PATH", str(db_path))
    monkeypatch.setenv("REGISTRY_ADMIN_SECRET", "dev-admin-secret")
    monkeypatch.setenv("LOG_FORMAT", "pretty")
    monkeypatch.setenv("LOG_LEVEL", "warning")
    # Avoid live LLM provider keys leaking into tests.
    monkeypatch.setenv("GOOGLE_API_KEY", "")
    monkeypatch.setenv("MINIMAX_API_KEY", "")

    from vellum.config.settings import reload_settings

    reload_settings()
    yield {"db_path": str(db_path)}
    reload_settings()


# ---------------------------------------------------------------------------
# FastAPI app + httpx client
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def client(settings_env):
    """An httpx.AsyncClient bound to a fresh FastAPI app, with lifespan running."""
    from vellum.app import create_app

    app = create_app()
    async with LifespanManager(app):
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as c:
            yield c


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def make_company(client):
    """Factory that creates a company via the API and returns the parsed JSON.

    The returned dict includes ``private_key_hex`` (auto-generated by the API).
    """

    async def _make(name: str = "Test Co") -> dict[str, Any]:
        resp = await client.post(
            "/api/companies",
            json={
                "name": name,
                "auto_generate": True,
                "admin_secret": "dev-admin-secret",
            },
        )
        assert resp.status_code == 200, resp.text
        return resp.json()

    return _make


def sign_text(text: str, private_key_hex: str) -> tuple[str, str]:
    """Hash + sign ``text``. Returns (sha256_hex, signature_hex)."""
    from vellum.auth.ecdsa import hash_text, sign_hash

    h = hash_text(text)
    sig = sign_hash(h, private_key_hex)
    return h, sig


@pytest.fixture
def signer():
    """Convenience fixture exposing :func:`sign_text` as a callable."""
    return sign_text


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
